### ISSUE TITLE
Tree: Level Order Traversal

### ISSUE THREAD

**Issue by raychenon** [raychenon/algorithms#30]
https://www.hackerrank.com/challenges/tree-level-order-traversal/problem

**Comment by AKSHAYA8219** [comment]
Try this function,
def levelOrder(root):
    if root is None:
        return
    q = [root]
    while(len(q) > 0):
        n = q.pop(0)
        print(n.info,end=" ")
        if n.left:
            q.append(n.left)
        if n.right:
            q.append(n.right)
